services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads  
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/auth_db
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:   
  backenduploads: 

networks:
  mynetwork:
    driver: bridge
